#!/usr/bin/python
# -*- coding: latin-1 -*-
import os, sys


num = int(input('Digite um número:'))
print('''Escolha uma das opções de converção:
Opção 1: Binário
Opção 2: Octal
Opção 3: Hexadecimal''')
opção = int(input('Digite a opção:'))

if opção == 1:
    print('{} convertido para BINÁRIO é igual a {}'.format(num, bin(num)[2:]))
elif opção == 2:
    print('{} convertido para OCTAL é igua a {}'.format(num, oct(num)[2:]))
elif opção == 3:
    print('{} convertiso para HEXADECIMAL é igual a {}'.format(num, hex(num)[2:]))
else:
    print('Opção inválida. Tente novamente.')
